baseURL = "https://dataplatform-docs.az3-cfes-eastus2-npe-asev3.appserviceenvironment.net/"
canonifyURLs = true # true -> all relative URLs would instead be canonicalized using baseURL
relativeURLs = true # true -> rewrite all relative URLs to be relative to the current content
uglyURLs = true     # true -> basic/index.html -> basic.html

themesdir = "themes"
theme = "hugo-theme-relearn"

languageCode = "en"
defaultContentLanguage = "en"
disableLanguages = ['pir']

title = "Cloudifyi Solutions"
usePageBundles = true
disableHugoGeneratorInject = true
ignorefiles = [ "examples/.*" ]
[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[markup]
  [markup.highlight]
    guessSyntax = false
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'content'
    target = 'content'

  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'
  [[module.mounts]]
    source = 'content/images'
    target = 'static/images'
  [[module.mounts]]
    source = 'static/images'
    target = 'static/images'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'

[Languages]
  [Languages.en]
    title = "Cloudifyi Solutions"
    weight = 1
    languageName = "English"
    landingPageName = "<i class='fas fa-home'></i> Home"

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-tags'></i> Tags"
    url = "tags/"
    weight = 40

[params]
  editURL = "https://github.com/cloudifyisolutions/Cloudifyi-Hugo-Site/"
  description = "Cloudifyi Solutions - Documentation"
  author = "Cloudifyi Solutions Team"
  showVisitedLinks = true
  collapsibleMenu = true
  disableBreadcrumb = false
  disableInlineCopyToClipBoard = true
  disableNextPrev = false
  disableLandingPageButton = true
  titleSeparator = "::"
  themeVariant = [ "zen-light"]
  disableSeoHiddenPages = true
  
  additionalContentLanguage = [ "en" ]
